//! The `p1:module/authorization-policy` world's bindings, generated by `wit-bindgen` into
//! [`generated`](self::generated) for the authorization-policy components.
//!
//! The same separate-crate pattern as `p1-bindings-tool`: the `export!` macro `wit-bindgen`
//! writes needs `unsafe`, and every crate of this workspace forbids `unsafe_code` (the
//! workspace lint), so `generate!` runs in this crate and `pub_export_macro` exports the macro
//! a component crate calls. The expansion then belongs to another crate's macro, and no crate
//! ever loosens the lint.
#![forbid(unsafe_code)]

/// The generated bindings for the `authorization-policy` world of the WIT package in
/// [`modules/wit`].
///
/// [`modules/wit`]: ../../wit
pub mod generated {
    wit_bindgen::generate!({
        path: "../wit",
        world: "authorization-policy",
        pub_export_macro: true,
        default_bindings_module: "p1_bindings_authorization_policy::generated",
    });
}
