//! The `p1:module/provider` world's bindings, generated by `wit-bindgen` into
//! [`generated`](self::generated) for the provider components.
//!
//! The same separate-crate pattern as `p1-bindings-tool`: the `export!` macro `wit-bindgen`
//! writes needs `unsafe`, and every crate of this workspace forbids `unsafe_code` (the
//! workspace lint), so `generate!` runs in this crate and `pub_export_macro` exports the macro
//! a component crate calls. The expansion then belongs to another crate's macro, and no crate
//! ever loosens the lint.
#![forbid(unsafe_code)]

/// The generated bindings for the `provider` world of the WIT package in [`modules/wit`].
///
/// [`modules/wit`]: ../../wit
// The generated lifting and lowering functions take one argument per flattened field of
// the world's records (`http-request`, `provider-request`), which the frozen WIT decides.
#[allow(clippy::too_many_arguments)]
pub mod generated {
    wit_bindgen::generate!({
        path: "../wit",
        world: "provider",
        pub_export_macro: true,
        default_bindings_module: "p1_bindings_provider::generated",
    });
}
