//! The `p1:module/tool` world's bindings, generated by `wit-bindgen` into
//! [`generated`](self::generated) for the component crates of this workspace.
//!
//! Separate crate, one reason: the `export!` macro `wit-bindgen` writes needs `unsafe`, and
//! every crate of this workspace forbids `unsafe_code` (the root workspace lint). With
//! `generate!` in the same crate as the `export!(Type)` call, the macro expands inside the
//! crate that forbids `unsafe` and the build fails; with the bindings in their own crate and
//! `pub_export_macro`, the component crate calls `<this crate>::generated::export!(Type)` and
//! no crate ever loosens the lint. A second crate also gives the whole workspace one place
//! where the generated code is (so a boundary check can tell generated from handwritten
//! code) and one place where the WIT path and the bindings module name are stated.
#![forbid(unsafe_code)]

/// The generated bindings for the `tool` world of the WIT package in [`modules/wit`].
///
/// `default_bindings_module` tells the generated code how to name itself, and
/// `pub_export_macro` exports the `export!` macro that component crates call.
///
/// [`modules/wit`]: ../../wit
pub mod generated {
    wit_bindgen::generate!({
        path: "../wit",
        world: "tool",
        pub_export_macro: true,
        default_bindings_module: "p1_bindings_tool::generated",
    });
}
