#!/usr/bin/env bash
# Machine-local cargo settings for a checkout/worktree (untracked; CI is unaffected).
#
# Small SSD + 7 GB RAM, several agents building at once:
#  - RAM: every rustc goes through scripts/rustc-serial, a machine-wide semaphore
#    (2 slots), so compiles are bounded globally, not per cargo invocation.
#  - Disk: the MAIN checkout builds into ../phaseone-target. A worktree gets its OWN
#    target/ — seeded with HARDLINKS of the main target's third-party artifacts, so the
#    expensive dependencies cost no extra disk and are never rebuilt. Only the small p1
#    crates are compiled per worktree; `git worktree remove --force` frees them.
#  - Why not one shared target dir (the first design, D12): cargo names a workspace
#    member's artifacts from its path RELATIVE to the workspace root, so every worktree's
#    `p1-core` maps to the same files and freshness is judged by mtime — one worktree
#    silently links another's build (observed 2026-09-20: a stale `unimplemented!` stub
#    linked into a worktree whose core was implemented). D20.
#
#   scripts/local-cargo-config.sh [checkout-dir]     (default: this checkout)
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
checkout="$(cd "${1:-$here}" && pwd)"
main="$(git -C "$here" worktree list --porcelain | sed -n '1s/^worktree //p')"
seed="${P1_SHARED_TARGET:-$(dirname "$main")/phaseone-target}"

mkdir -p "$checkout/.cargo"
if [ "$checkout" = "$main" ]; then
  target="$seed"
  mkdir -p "$target"
else
  target="$checkout/target"
  if [ ! -d "$target" ] && [ -d "$seed/debug" ]; then
    cp -al "$seed" "$target"
    # Drop everything belonging to workspace members: they must be built from THIS tree.
    find "$target" -depth \( -name 'p1_*' -o -name 'libp1_*' -o -name 'p1-*' -o -name 'p1' \
         -o -name 'acceptance_*' -o -name 'impl_*' -o -name 'incremental' \) \
         -exec rm -rf {} + 2>/dev/null || true
    find "$target/debug" -maxdepth 1 -type f -delete 2>/dev/null || true
  fi
fi
# The wrapper must be reachable from INSIDE the shell sandbox, which hides the home directory
# except the workspace itself — so a checkout uses its own copy when it has one (dogfood run
# 2026-09-20: the agent found the main checkout's wrapper invisible, regenerated this file and
# thereby left the machine-wide semaphore).
wrapper="$main/scripts/rustc-serial"
[ -x "$checkout/scripts/rustc-serial" ] && wrapper="$checkout/scripts/rustc-serial"
cat > "$checkout/.cargo/config.toml" <<CFG
# Generated by scripts/local-cargo-config.sh — machine-local, not committed.
[build]
target-dir = "$target"
jobs = 2
incremental = false
rustc-wrapper = "$wrapper"

[profile.dev.package."*"]
debug = false
CFG
echo "cargo config: $checkout/.cargo/config.toml -> target-dir $target ($(du -sh "$target" 2>/dev/null | cut -f1))"
