#!/usr/bin/env bash
# Machine-local cargo settings for a checkout/worktree (untracked; CI is unaffected).
#
# Small SSD + 7 GB RAM: ALL p1 checkouts and worktrees share ONE target directory.
#  - third-party dependencies are compiled and stored once, not once per worktree;
#  - cargo's lock on the shared build directory serialises compilation, so parallel
#    agents never compile at the same time (a second cargo prints "Blocking waiting
#    for file lock on build directory" and simply waits — that is intended);
#  - incremental caches are off: they multiply per worktree and dominate disk use.
#
#   scripts/local-cargo-config.sh [checkout-dir]     (default: this checkout)
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
checkout="$(cd "${1:-$root}" && pwd)"
shared="${P1_SHARED_TARGET:-$(dirname "$(git -C "$root" worktree list --porcelain | sed -n '1s/^worktree //p')")/phaseone-target}"

mkdir -p "$checkout/.cargo" "$shared"
cat > "$checkout/.cargo/config.toml" <<CFG
# Generated by scripts/local-cargo-config.sh — machine-local, not committed.
[build]
target-dir = "$shared"
jobs = 2
incremental = false

[profile.dev.package."*"]
debug = false
CFG
echo "cargo config: $checkout/.cargo/config.toml -> target-dir $shared"
