#!/usr/bin/env python3
"""Tests for scripts/check-module-boundaries.sh — stdlib only, stub tools on PATH.

The script under test runs in a temporary repository that holds the frozen data the default
mode reads (modules/capabilities.toml, modules/wit/worlds.wit, the module workspace manifest,
two module packages and the build outputs scripts/build-modules.sh would publish) with stub
`wasm-tools` and `cargo` tools first on PATH: no real toolchain, no network and no user
directory is touched. The shipping mode reads the production graph the stub `cargo` prints, so
the classification, the inventory, the native fallback list and the last line are checked
against a graph this file owns; the same temporary repository is what the default mode's golden
output is pinned over.

The stub cargo graph is written to `cargo-tree.txt` in the temporary repository, one `cargo
tree --prefix depth` line per crate; the stub wasm-tools prints the world of the fixture
package the path names, so a package's `.imports` and `.wit` can be checked against it.
"""
from __future__ import annotations

import os
import pathlib
import shutil
import stat
import subprocess
import sys
import tempfile
import textwrap
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "check-module-boundaries.sh"

TOOL = "p1-module-demo"
CONTEXT = "p1-module-context"

# The extracted worlds of the two fixture packages: what the stub wasm-tools prints for a
# component and what the build outputs carry as <package>.wit.
TOOL_WORLD = """world root {
  import p1:module/control@1.0.0;
  export demo: func();
}
"""

CONTEXT_WORLD = """world root {
  import p1:module/control@1.0.0;
  export summarize: func();
}
"""

CAPABILITIES = """\
# The per-class capability allocation of the fixture, in the shape of the frozen one.
type-only = ["types", "worker-types"]

[tool]
imports = ["types", "control", "clock"]

[context-policy]
imports = ["types", "control", "summary"]
"""

WORLDS = """\
world tool {
  import p1:module/control@1.0.0;
  export demo: func();
}

world context-policy {
  import p1:module/control@1.0.0;
  export summarize: func();
}
"""

# The golden output of the default mode over the fixture's build outputs: the same lines and
# exit code as the script printed before --shipping was added, which is what B-S7-2/D059 froze.
GOLDEN = """\
check-module-boundaries: p1-module-context: ok
check-module-boundaries: p1-module-demo: ok
check-module-boundaries: p1-module-protocol: ok
check-module-boundaries: p1-module-runtime: ok
check-module-boundaries: p1-module-tests: ok
check-module-boundaries: p1-bindings-demo: ok generated by wit_bindgen::generate!: its expansion contains unsafe code the lint does not see because it expands from another crate's macro; the crate compiles under unsafe_code = "forbid"
check-module-boundaries: p1-module-context: ok
check-module-boundaries: p1-module-demo: ok
check-module-boundaries: clean (2 packages, 6 crates)
"""


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_exec(path: pathlib.Path, text: str) -> None:
    write(path, text)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def package_manifest(crate: str, name: str, kind: str, capabilities: str) -> str:
    return textwrap.dedent(
        f"""\
        [package]
        name = "{crate}"
        version = "0.0.1"
        edition = "2024"

        [lints]
        workspace = true

        [package.metadata.p1-module]
        name = "{name}"
        kind = "{kind}"
        world = "p1:module/{kind}@1.0.0"
        protocol = "1.0"
        capabilities = [{capabilities}]
        variant = "default"
        """
    )


def build_manifest(name: str, kind: str) -> str:
    return textwrap.dedent(
        f"""\
        {{
          "name": "{name}",
          "kind": "{kind}",
          "world": "p1:module/{kind}@1.0.0",
          "protocol": "1.0",
          "capabilities": ["control"],
          "variant": "default",
          "digest": "sha256:0000000000000000000000000000000000000000000000000000000000000000",
          "size": 15
        }}
        """
    )


class Harness:
    """A temporary repository with the fixture, a stub cargo graph and a stub wasm-tools."""

    def __init__(self) -> None:
        self.tmp = tempfile.TemporaryDirectory(prefix="boundaries-test-")
        self.base = pathlib.Path(self.tmp.name)
        self.repo = self.base / "repo"
        self.bin = self.base / "bin"
        self.tree = self.repo / "cargo-tree.txt"
        (self.repo / "scripts").mkdir(parents=True)
        shutil.copy2(SCRIPT, self.repo / "scripts" / "check-module-boundaries.sh")

        write(self.repo / "Cargo.toml", WORKSPACE_ROOT)
        write(self.repo / "modules" / "Cargo.toml", MODULE_WORKSPACE)
        write(self.repo / "modules" / "capabilities.toml", CAPABILITIES)
        write(self.repo / "modules" / "wit" / "worlds.wit", WORLDS)
        for crate, name, kind, capabilities in (
            (TOOL, "p1/demo", "tool", '"control"'),
            (CONTEXT, "p1/context/summarizing", "context-policy", '"control"'),
        ):
            write(
                self.repo / "modules" / crate / "Cargo.toml",
                package_manifest(crate, name, kind, capabilities),
            )
            write(self.repo / "modules" / crate / "src" / "lib.rs", "// the fixture package\n")
            self.publish(crate, name, kind, TOOL_WORLD if crate == TOOL else CONTEXT_WORLD)
        # A bindings crate is a workspace member and no package: the default mode reports its
        # generated code instead of its boundary, and the fixture keeps it plain.
        write(
            self.repo / "modules" / "p1-bindings-demo" / "Cargo.toml",
            textwrap.dedent(
                """\
                [package]
                name = "p1-bindings-demo"
                version = "0.0.1"
                edition = "2024"

                [lints]
                workspace = true
                """
            ),
        )
        write(
            self.repo / "modules" / "p1-bindings-demo" / "src" / "lib.rs",
            "wit_bindgen::generate!({ world: \"fixture\" });\n",
        )
        for crate in ("p1-module-runtime", "p1-module-protocol", "p1-module-tests"):
            write(
                self.repo / "crates" / crate / "Cargo.toml",
                textwrap.dedent(
                    f"""\
                    [package]
                    name = "{crate}"
                    version = "0.0.1"
                    edition = "2024"

                    [lints]
                    workspace = true
                    """
                ),
            )
            write(self.repo / "crates" / crate / "src" / "lib.rs", "// the fixture crate\n")

        write_exec(self.bin / "wasm-tools", WASM_TOOLS_STUB)
        write_exec(self.bin / "cargo", CARGO_STUB)
        self.set_tree("")

    def publish(self, crate: str, name: str, kind: str, world: str) -> None:
        """The five build outputs of scripts/build-modules.sh for one fixture package."""
        out = self.repo / "modules" / "target" / "p1-modules" / crate
        write(out / f"{crate}.wasm", f"component bytes of {crate}\n")
        write(out / f"{crate}.wit", world)
        write(out / f"{crate}.imports", "p1:module/control@1.0.0\n")
        write(out / f"{crate}.manifest.json", build_manifest(name, kind))

    def set_tree(self, text: str) -> None:
        write(self.tree, text)

    def tree_with(self, *crates: str) -> str:
        """A `cargo tree --prefix depth` graph of p1-host over the named fixture crates."""
        lines = [f"0p1-host v0.0.1 ({self.repo}/crates/p1-host)"]
        lines += [f"1{crate} v0.0.1 ({self.repo}/crates/{crate})" for crate in crates]
        lines += ["1serde v1.0.229", "2serde_core v1.0.229"]
        return "\n".join(lines) + "\n"

    def run(self, *args: str) -> subprocess.CompletedProcess[str]:
        env = {
            "PATH": os.pathsep.join([str(self.bin), os.path.dirname(sys.executable), "/usr/bin", "/bin"]),
            "HOME": str(self.base),
            "LC_ALL": "C",
        }
        return subprocess.run(
            ["bash", str(self.repo / "scripts" / "check-module-boundaries.sh"), *args],
            cwd=self.repo,
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )

    def cleanup(self) -> None:
        self.tmp.cleanup()


class DefaultModeTests(unittest.TestCase):
    """The mode without --shipping: the same output and exit codes as before the option."""

    def harness(self) -> Harness:
        h = Harness()
        self.addCleanup(h.cleanup)
        return h

    def test_default_mode_output_is_the_golden_output(self) -> None:
        h = self.harness()
        result = h.run()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(result.stdout, GOLDEN)

    def test_default_mode_reports_a_finding_and_exits_1(self) -> None:
        h = self.harness()
        imports = h.repo / "modules" / "target" / "p1-modules" / CONTEXT / f"{CONTEXT}.imports"
        imports.write_text("p1:module/clock@1.0.0\n", encoding="utf-8")
        result = h.run()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(
            f"check-module-boundaries: {CONTEXT}: FINDING: {CONTEXT}.imports does not match the component's "
            "extracted world; imports clock, not in the context-policy allocation",
            result.stdout,
        )
        self.assertEqual(result.stdout.splitlines()[-1], "check-module-boundaries: 2 finding(s)")

    def test_an_unknown_option_still_exits_2_with_the_usage(self) -> None:
        h = self.harness()
        result = h.run("--nope")
        self.assertEqual(result.returncode, 2)
        self.assertIn("check-module-boundaries: unknown argument --nope", result.stderr)
        self.assertIn("usage: scripts/check-module-boundaries.sh [--output-dir <dir>]", result.stderr)
        self.assertIn("Exit 0 when clean, 1 when there is a finding, 2 on a usage or tool error.", result.stderr)

    def test_help_documents_the_shipping_option_and_exits_0(self) -> None:
        h = self.harness()
        result = h.run("--help")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("usage: scripts/check-module-boundaries.sh [--output-dir <dir>]", result.stdout)
        self.assertIn("--shipping", result.stdout)
        self.assertIn("--release-manifest <file>", result.stdout)


class ShippingModeTests(unittest.TestCase):
    """--shipping (D059): the graph, the classification, the inventory and the fallbacks."""

    def harness(self, *crates: str) -> Harness:
        h = Harness()
        self.addCleanup(h.cleanup)
        h.set_tree(h.tree_with(*crates))
        return h

    def test_every_workspace_crate_of_the_graph_is_classified(self) -> None:
        h = self.harness(
            "p1-assembly", "p1-contracts", "p1-core", "p1-module-protocol", "p1-module-runtime",
            "p1-context", "p1-tool-shell",
        )
        result = h.run("--shipping")
        classes = {
            "p1-host": "foundation",
            "p1-assembly": "foundation",
            "p1-contracts": "contracts",
            "p1-core": "core",
            "p1-module-protocol": "runtime",
            "p1-module-runtime": "runtime",
            "p1-context": "extension",
            "p1-tool-shell": "extension",
        }
        for crate, expected in classes.items():
            with self.subTest(crate=crate):
                self.assertRegex(
                    result.stdout, rf"(?m)^check-module-boundaries: shipping: graph: \d+ {crate} \({expected}: \S"
                )
        self.assertRegex(
            result.stdout,
            r"(?m)^check-module-boundaries: shipping: graph: 8 workspace crates, 2 external crates "
            r"\(cargo tree --locked --offline -p p1-host -e normal\)$",
        )

    def test_external_crates_are_counted_not_listed(self) -> None:
        h = self.harness("p1-core")
        result = h.run("--shipping")
        self.assertNotIn("serde", result.stdout)
        self.assertRegex(result.stdout, r"graph: 2 workspace crates, 2 external crates")

    def test_an_external_crate_repeated_in_the_graph_is_counted_once(self) -> None:
        # cargo prints an external crate a second time with ` (*)`, and one crate can be reached
        # at two versions: the figure counts distinct `<name> v<version>` pairs, the same base as
        # the deduplicated workspace figure beside it.
        h = self.harness("p1-core")
        h.set_tree(
            "\n".join(
                [
                    f"0p1-host v0.0.1 ({h.repo}/crates/p1-host)",
                    f"1p1-core v0.0.1 ({h.repo}/crates/p1-core)",
                    "2serde v1.0.229",
                    "2serde_core v1.0.229",
                    "1serde v1.0.229 (*)",
                    "1serde_json v1.0.145",
                    "2serde v1.0.229 (*)",
                    "2serde v1.0.228",
                    "",
                ]
            )
        )
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotIn("serde", result.stdout)
        self.assertRegex(
            result.stdout,
            r"(?m)^check-module-boundaries: shipping: graph: 2 workspace crates, 4 external crates "
            r"\(cargo tree --locked --offline -p p1-host -e normal\)$",
        )

    def test_a_reachable_extension_is_listed_with_its_path_and_the_package(self) -> None:
        h = self.harness("p1-tool-shell", "p1-context")
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(
            "check-module-boundaries: shipping: native fallback: p1-tool-shell (extension) "
            "via p1-host > p1-tool-shell; no module package ships it yet",
            result.stdout,
        )
        self.assertIn(
            "check-module-boundaries: shipping: native fallback: p1-context (extension) "
            "via p1-host > p1-context; implements p1/context/summarizing (p1-module-context)",
            result.stdout,
        )
        self.assertEqual(result.stdout.splitlines()[-1], "check-module-boundaries: shipping: 2 native fallback(s)")

    def test_the_path_from_p1_host_is_printed_for_a_deeper_crate(self) -> None:
        h = Harness()
        self.addCleanup(h.cleanup)
        h.set_tree(
            "\n".join(
                [
                    f"0p1-host v0.0.1 ({h.repo}/crates/p1-host)",
                    f"1p1-assembly v0.0.1 ({h.repo}/crates/p1-assembly)",
                    f"2p1-tool-shell v0.0.1 ({h.repo}/crates/p1-tool-shell)",
                    "",
                ]
            )
        )
        result = h.run("--shipping")
        self.assertIn(
            "native fallback: p1-tool-shell (extension) via p1-host > p1-assembly > p1-tool-shell",
            result.stdout,
        )

    def test_a_crate_outside_the_frozen_table_is_a_finding(self) -> None:
        h = self.harness("p1-core", "p1-brand-new")
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(
            "check-module-boundaries: shipping: FINDING: p1-brand-new (depth 1) is not in the frozen classification table",
            result.stdout,
        )
        self.assertEqual(result.stdout.splitlines()[-1], "check-module-boundaries: shipping: 1 finding(s)")

    def test_an_empty_fallback_graph_is_clean_and_exits_0(self) -> None:
        h = self.harness("p1-assembly", "p1-contracts", "p1-core", "p1-module-runtime")
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotIn("native fallback:", result.stdout)
        # The native authorization policies p1-host still answers are named, but they are not a
        # crate of the graph: they do not count as a crate fallback.
        self.assertIn(
            "check-module-boundaries: shipping: native twin: p1-host (extension: the native authorization policies "
            "p1/policy/ask and p1/policy/full-access (crates/p1-host/src/policy.rs))",
            result.stdout,
        )
        self.assertEqual(
            result.stdout.splitlines()[-1],
            "check-module-boundaries: shipping: clean (5 crates, 2 packages, 0 native fallbacks)",
        )

    def test_the_import_inventory_names_every_shipped_package_and_its_imports(self) -> None:
        h = self.harness("p1-contracts", "p1-core")
        result = h.run("--shipping")
        self.assertIn(
            "check-module-boundaries: shipping: imports: context-policy p1-module-context "
            "(p1/context/summarizing): p1:module/control@1.0.0",
            result.stdout,
        )
        self.assertIn(
            "check-module-boundaries: shipping: imports: tool p1-module-demo (p1/demo): p1:module/control@1.0.0",
            result.stdout,
        )

    def test_output_dir_combines_with_shipping(self) -> None:
        h = self.harness("p1-contracts", "p1-core")
        other = h.base / "other-outputs"
        shutil.copytree(h.repo / "modules" / "target" / "p1-modules", other)
        result = h.run("--shipping", "--output-dir", str(other))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("imports: tool p1-module-demo (p1/demo): p1:module/control@1.0.0", result.stdout)

    def test_a_build_output_without_its_imports_is_a_finding(self) -> None:
        h = self.harness("p1-contracts", "p1-core")
        (h.repo / "modules" / "target" / "p1-modules" / TOOL / f"{TOOL}.imports").unlink()
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(
            "check-module-boundaries: shipping: FINDING: modules/target/p1-modules/p1-module-demo/p1-module-demo.imports is missing",
            result.stdout,
        )
        self.assertEqual(result.stdout.splitlines()[-1], "check-module-boundaries: shipping: 1 finding(s)")

    def test_shipping_needs_no_wasm_tools(self) -> None:
        h = self.harness("p1-contracts", "p1-core")
        (h.bin / "wasm-tools").unlink()
        result = h.run("--shipping")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_the_release_manifest_names_the_shipped_packages(self) -> None:
        h = self.harness("p1-contracts", "p1-core")
        manifest = h.base / "manifest.json"
        write(
            manifest,
            textwrap.dedent(
                """\
                {
                  "components": [
                    {
                      "kind": "tool",
                      "name": "p1/demo",
                      "path": "packages/p1-demo/p1-demo.wasm"
                    },
                    {
                      "kind": "tool",
                      "name": "p1/gone",
                      "path": "packages/p1-gone/p1-gone.wasm"
                    }
                  ],
                  "format": "p1-release-manifest/1"
                }
                """
            ),
        )
        result = h.run("--shipping", "--release-manifest", str(manifest))
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("imports: the components of", result.stdout)
        self.assertIn("imports: tool p1-module-demo (p1/demo): p1:module/control@1.0.0", result.stdout)
        self.assertNotIn("imports: context-policy", result.stdout)
        self.assertIn(
            "check-module-boundaries: shipping: not shipped: p1/context/summarizing (p1-module-context) is built "
            f"and {manifest} does not name it",
            result.stdout,
        )
        self.assertIn(
            f"check-module-boundaries: shipping: FINDING: {manifest} names p1/gone, and no build output under "
            "modules/target/p1-modules does",
            result.stdout,
        )

    def test_a_release_manifest_without_shipping_is_a_usage_error(self) -> None:
        h = self.harness()
        result = h.run("--release-manifest", str(h.base / "manifest.json"))
        self.assertEqual(result.returncode, 2)
        self.assertIn(
            "check-module-boundaries: --release-manifest is a shipping option; add --shipping", result.stderr
        )


WORKSPACE_ROOT = textwrap.dedent(
    """\
    [workspace]
    resolver = "3"
    members = ["crates/*"]

    [workspace.lints.rust]
    unsafe_code = "forbid"
    """
)

MODULE_WORKSPACE = textwrap.dedent(
    """\
    [workspace]
    resolver = "3"
    members = ["p1-module-*", "p1-bindings-*"]

    [workspace.lints.rust]
    unsafe_code = "forbid"
    """
)

CARGO_STUB = """\
#!/usr/bin/env bash
# The stub cargo: the graph this test fixed, for the one call the shipping mode makes.
if [ "${1:-}" = tree ]; then
  exec cat "$PWD/cargo-tree.txt"
fi
echo "stub cargo: unsupported call $*" >&2
exit 1
"""

WASM_TOOLS_STUB = f"""\
#!/usr/bin/env bash
# The stub wasm-tools: the fixture world of the component the path names.
if [ "${{1:-}}" = component ] && [ "${{2:-}}" = wit ]; then
  case "${{3:-}}" in
    *context*)
      cat <<'WORLD'
{CONTEXT_WORLD}WORLD
      ;;
    *)
      cat <<'WORLD'
{TOOL_WORLD}WORLD
      ;;
  esac
  exit 0
fi
echo "stub wasm-tools: unsupported call $*" >&2
exit 1
"""


if __name__ == "__main__":
    sys.exit(unittest.main())
