//! The `p1:module/context-policy` world's bindings, generated by `wit-bindgen` into
//! [`generated`](self::generated) for the context-policy component crates of this workspace.
//!
//! The binding-crate pattern of `docs/design/modules/package.md`: the `export!` macro
//! `wit-bindgen` writes needs `unsafe`, every crate of this workspace forbids `unsafe_code`,
//! so the macro is defined here and expanded in the component crate.
#![forbid(unsafe_code)]

/// The generated bindings for the `context-policy` world of the WIT package in
/// [`modules/wit`].
///
/// [`modules/wit`]: ../../wit
pub mod generated {
    wit_bindgen::generate!({
        path: "../wit",
        world: "context-policy",
        pub_export_macro: true,
        default_bindings_module: "p1_bindings_context_policy::generated",
    });
}
